const CONSTANTS = {
  PROJECT_NAME: 'MITD OS',
  LAYOUT_PREFIX: '/main',
  API_V1_BASE_URL: process.env.REACT_APP_API_V1_BASE_URL,
  API_V2_BASE_URL: process.env.REACT_APP_API_V2_BASE_URL,
  API_V1_FILE_STORAGE_BASE_URL:
    process.env.REACT_APP_API_V1_FILE_STORAGE_BASE_URL,

  LOGIN_CHECK_TIME: 30, //min

  FILE_STORAGE_USER_ID: process.env.REACT_APP_FILE_STORAGE_USER_ID,
  FILE_STORAGE_BUCKET_NAME: process.env.REACT_APP_FILE_STORAGE_BUCKET_NAME,
};

export default CONSTANTS;
